### ISSUE TITLE
[WORKFLOW] npm ci error installing 'react undefined'

### ISSUE THREAD

**Issue by JuanGidoni** [JuanGidoni/justdoit#2]
When running new workflows, the ones that need to run for node js are failing.

> npm ci react undefined

**Comment by juanigidt** [comment]
Some of the research that I did said that you need to remove `package-lock.json` but seems like isn't working because the logs are asking for it:
> Error: Dependencies lock file is not found in /home/runner/work/justdoit/justdoit. Supported file patterns: package-lock.json,npm-shrinkwrap.json,yarn.lock
